version: '3.8'
services:
  face-recognition:
    build: .
    volumes:
      - ./data:/app/data
      - ./runs:/app/runs
    command: >
      python src/yolo_batch.py 
      --input-dir /app/data/images 
      --output-dir /app/runs/detect
